### ISSUE TITLE
Replit is not supported!

### ISSUE THREAD

**Issue by testbot-github** [Tomato6966/Simple-Multiguild-Number-Counter-djs-v13#1]
**Replit doesn't support ENMAP (sqlite)**

This is because replit always keeps a snapshot of things before you left, and when you get back onto the repl it reverts to the snapshot that you were on last, therefore reverting your data.

The best Database to use in replit is `MongoDB`

**Comment by testbot-github** [comment]
@Tomato6966 Please pin and close this issue

**Comment by Tomato6966** [comment]
No, the best db for replit is replitDB

+ it supports enmap, just get hacker

**Comment by testbot-github** [comment]
> No, the best db for replit is replitDB
> 
> * it supports enmap, just get hacker

oh ok
